### ISSUE TITLE
link rel=preload must have a valid `as` value

### ISSUE THREAD

**Issue by stakeworks** [daveross/http2-server-push#10]
I got this warning in Chrome "<link rel=preload>`must have a valid`as` value".

On line 74 the 'as' is set as 'stylesheet' for css files:
function http2_link_link_as( $current_hook ) {
    return 'style_loader_src' === $current_hook ? 'stylesheet' : 'script';
}

This must be 'style', see https://w3c.github.io/preload/#server-push-http-2

https://wordpress.org/plugins/http2-server-push/

**Comment by dana-ross** [comment]
Well that's lovely. They changed the preload spec to match the server-push semantics. I guess that's actually a good thing.

http://www.w3.org/TR/2015/WD-preload-20150721/ is what I based my code on, but I can simplify some things now that everything is the same across the board.

Thanks for reporting this!
