### ISSUE TITLE
No headers with Wordfence caching turned on

### ISSUE THREAD

**Issue by sdayman** [daveross/http2-server-push#11]
The Link headers don't show up on my pages when I have any Wordfence caching turned on. Whether it's Falcon cache, or their standard cache, Cloudflare doesn't get the headers. As soon as I set Wordfence to No Caching, the headers begin showing up. It wouldn't surprise me if the Wordfence cache mechanism causes these resources to not be pushed because your documentation states that Plugin output code won't be affected.

My site is full SSL (Let's Encrypt) and all URLs begin with https on Apache at DreamHost sitting behind Cloudflare.

Any ideas what the conflict is or how I can track the problem? Or a workaround due to Wordfence caching?

**Comment by dana-ross** [comment]
Wordfence's cache just captures the page body with a PHP output buffer & writes it to disk. Unfortunately, that completely ignores the headers.

**Comment by sdayman** [comment]
Thanks for the quick response. It totally makes sense now. At least your backup link directives are preserved in the document head.
