### ISSUE TITLE
Push Fonts (woff2, woff)?

### ISSUE THREAD

**Issue by collinbarrett** [daveross/http2-server-push#12]
This plugin works great! I noticed it does not apply to fonts such as woff2 and woff. Is this possible?

**Comment by dana-ross** [comment]
That would be cool, but WordPress doesn't have a way for themes & plugins to enqueue fonts the way they do with CSS & JavaScript files.

But if you wanted to push a font file yourself, you could use code like (note: this is untested):

``` php
function server_push_font_files() {
  $font_src = '/path/to/font.woff';

  // Send the Link header for server push
  header(
    sprintf(
      'Link: <%s>; rel=preload; as=font',
      esc_url( http2_link_url_to_relative_path( $font_src ) )
    )
    , false
  );
}
add_action('init', 'server_push_font_files');

// Add a <link rel="preload"> tag as a fallback
function preload_font_files() {
  $font_src = '/path/to/font.woff';
  printf( '<link rel="preload"  href="%s" as="font">', esc_url($font_src) );
}
add_action( 'wp_head', 'preload_font_files', 99, 1);
```

**Comment by collinbarrett** [comment]
Great, thanks! I'll give that a shot.

**Comment by collinbarrett** [comment]
Hmm, interesting... It does work; however, the fonts end up getting delivered sent three times now. They are pushed right away and then loaded after all of the pushed files twice. One of those extra loads might have to do with your fallback suggestion and the other with how the theme enqueues the font files (I used the FontSquirrel font generator)? If you have any ideas, that'd be great. If not, though, I'll keep playing with it.

Thanks!

**Comment by collinbarrett** [comment]
In case anyone else ever comes across this, I discovered a non-code way to push fonts/images. See [here](https://collinmbarrett.com/http2-server-push-wordpress/#wordpress-implementation).
