### ISSUE TITLE
Various Errors

### ISSUE THREAD

**Issue by kraftbj** [daveross/http2-server-push#2]
On the admin side: 
`Warning: Cannot modify header information - headers already sent by (output started at /srv/www/master/html/wp-includes/script-loader.php:1147) in /wp-content/plugins/http2-server-push/http2-server-push.php on line 35`

Front-end:
`Warning: ob_start(): function '' not found or invalid function name in /srv/www/master/html/wp-includes/plugin.php on line 525`

`Notice: ob_start(): failed to create buffer in /srv/www/master/html/wp-includes/plugin.php on line 525`

I'm sure this is probably due to random plugins on my end, but wanted to note it somewhere as it'd be nice to be able to determine a way to work around it.

**Comment by suzannealdrich** [comment]
I'm having this issue too. Will try to see if the latest commits help ameliorate.

**Comment by dana-ross** [comment]
The v1.1 release should address these errors.
